name: 'Setup and install'
description: 'Common setup steps for CI jobs'

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v5
      with:
        run_install: false

    - uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
        check-latest: true

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
