import {
  MenuArrow,
  MenuBackdrop,
  MenuCheckboxItem,
  MenuContent,
  MenuGroup,
  MenuItem,
  MenuLabel,
  MenuLinkItem,
  MenuPortal,
  MenuRadioGroup,
  MenuRoot,
  MenuSeparator,
  MenuShortcut,
  MenuSub,
  MenuSubContent,
  MenuSubTrigger,
  MenuTrigger,
} from "./menu"

export {
  MenuArrow,
  type MenuArrowProps,
  MenuBackdrop,
  type MenuBackdropProps,
  MenuCheckboxItem,
  type MenuCheckboxItemProps,
  MenuContent,
  type MenuContentProps,
  MenuGroup,
  type MenuGroupProps,
  MenuItem,
  type MenuItemProps,
  type MenuItemVariant,
  MenuLabel,
  type MenuLabelProps,
  MenuLinkItem,
  type MenuLinkItemProps,
  MenuPortal,
  type MenuPortalProps,
  MenuRadioGroup,
  type MenuRadioGroupProps,
  MenuRoot,
  type MenuRootProps,
  MenuSeparator,
  type MenuSeparatorProps,
  MenuShortcut,
  type MenuShortcutProps,
  MenuSub,
  MenuSubContent,
  type MenuSubContentProps,
  type MenuSubProps,
  MenuSubTrigger,
  type MenuSubTriggerProps,
  MenuTrigger,
  type MenuTriggerProps,
} from "./menu"

export const Menu = {
  Arrow: MenuArrow,
  Backdrop: MenuBackdrop,
  CheckboxItem: MenuCheckboxItem,
  Content: MenuContent,
  Group: MenuGroup,
  Item: MenuItem,
  Label: MenuLabel,
  LinkItem: MenuLinkItem,
  Portal: MenuPortal,
  RadioGroup: MenuRadioGroup,
  Root: MenuRoot,
  Separator: MenuSeparator,
  Shortcut: MenuShortcut,
  Sub: MenuSub,
  SubContent: MenuSubContent,
  SubTrigger: MenuSubTrigger,
  Trigger: MenuTrigger,
} as const
