coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: false

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: patch
        target: 80%
        threshold: 0%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
