import {
  NavigationMenuArrow,
  NavigationMenuBackdrop,
  NavigationMenuContent,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuPopup,
  NavigationMenuPortal,
  NavigationMenuPositioner,
  NavigationMenuRoot,
  NavigationMenuTrigger,
  NavigationMenuViewport,
} from "./navigation-menu"

export {
  NavigationMenuArrow,
  type NavigationMenuArrowProps,
  NavigationMenuBackdrop,
  type NavigationMenuBackdropProps,
  NavigationMenuContent,
  type NavigationMenuContentProps,
  NavigationMenuItem,
  type NavigationMenuItemProps,
  NavigationMenuLink,
  type NavigationMenuLinkProps,
  NavigationMenuList,
  type NavigationMenuListProps,
  NavigationMenuPopup,
  type NavigationMenuPopupProps,
  NavigationMenuPortal,
  type NavigationMenuPortalProps,
  NavigationMenuPositioner,
  type NavigationMenuPositionerProps,
  NavigationMenuRoot,
  type NavigationMenuRootProps,
  NavigationMenuTrigger,
  type NavigationMenuTriggerProps,
  NavigationMenuViewport,
  type NavigationMenuViewportProps,
} from "./navigation-menu"

export const NavigationMenu = {
  Arrow: NavigationMenuArrow,
  Backdrop: NavigationMenuBackdrop,
  Content: NavigationMenuContent,
  Item: NavigationMenuItem,
  Link: NavigationMenuLink,
  List: NavigationMenuList,
  Popup: NavigationMenuPopup,
  Portal: NavigationMenuPortal,
  Positioner: NavigationMenuPositioner,
  Root: NavigationMenuRoot,
  Trigger: NavigationMenuTrigger,
  Viewport: NavigationMenuViewport,
} as const
